### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by skroczek** [schmittjoh/object-routing#8]
Hi,

in July I made three pull requests (#5, #6 and #7 ) for this repository. But so far I have not received any feedback from @schmittjoh. I'm sure that there are more popular projects to maintain, but some feedback would be very nice. :)

But there is an other reason why I'm creating this issue. Playing around with the tests and composer using "--prefer-lowest" I recognize that most of the tests fails. So I'm not sure if it is worth to fix this issue?

Thanks
Sebastian

**Comment by schmittjoh** [comment]
I think you can push the lowest dependencies up if needed. If someone is still on an older version, we have a release for that version already.

**Comment by schmittjoh** [comment]
The PRs look good, one needs to be rebased, the other ones are merged now. Thanks!

**Comment by skroczek** [comment]
Thanks for your fast reaction and merging again. I've made another pull request #9  to push the lowest dependencies up. But this library has no release yet. So I think it would a good idea to create a release before merging this PR and possible another after merging. This would also close issue #2.

**Comment by schmittjoh** [comment]
Thanks, that sounds like a sensible approach. I did just that. We now have two releases.
